version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./app
      target: /usr/src/app
    command: sh -c "npm run start" 
    ports:
      - 3000:3000
    stdin_open: true